version: '3'
services:
    server:
        # Docker hub
        # image: yfricke/experimental-satisfactory-server

        # Github Container registry
        image: ghcr.io/yannickfricke/experimental-satisfactory-ds-docker
        ports:
            - 15777:15777/udp
            - 15000:15000/udp
            - 7777:7777/udp
        volumes:
            - ./shared/SaveGames:/home/steam/.config/Epic/FactoryGame/Saved/SaveGames/server
        restart: unless-stopped
